apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krispy-api-role-binding
  #
  # The namespace of the RoleBinding determines where the permissions are granted.
  # This only grants permissions within the "development" namespace.
  namespace: default
subjects:
- kind: ServiceAccount
  name: krispy-api-account
roleRef:
  kind: ClusterRole
  name: krispy-api-role
  apiGroup: rbac.authorization.k8s.io