apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-k3os-15989
  labels:
    app: workshop-k3os-15989
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-k3os-15989
  template:
    metadata:
      labels:
       app: workshop-k3os-15989
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      nodeName: k3os-15989
      containers:
      - env:
        - name: DISPLAY
          value: :0.0
        image: jockdarock/postmantest:v0.0.2
        name: workshop-k3os-15989
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      restartPolicy: Always
      hostNetwork: true
