apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsktop-test
  labels:
    app: dsktop-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsktop-test
  template:
    metadata:
      labels:
       app: dsktop-test
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
      - env:
        - name: DISPLAY
          value: :0.0
        #image: jockdarock/dsktop-test:ubuntu18-04
        image: jockdarock/postmantest:v0.0.2
        name: dsktop-test
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      restartPolicy: Always
      hostNetwork: true
