apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080